PackageIdentifier: pan-nie.Nmail
PackageVersion: 0.4.7
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/pan-nie/Nmail/releases/download/v0.4.7/nmail-windows-x64.exe
    InstallerSha256: 87AE40976082B35AB0E1083D38C36BE602182F0D624D1FB4CBE5F2B416D7E110
    Commands:
      - nmail
ManifestType: installer
ManifestVersion: 1.6.0
